esphome:
  name: tigo-server
  friendly_name: "Tigo Server"

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      # UART optimizations to prevent packet loss (increased for 32MB PSRAM)
      CONFIG_UART_ISR_IN_IRAM: "y"
      CONFIG_UART_RX_BUFFER_SIZE: "8192"
      CONFIG_UART_TX_BUFFER_SIZE: "2048"
      # Reduce task switching overhead
      CONFIG_FREERTOS_HZ: "1000"
      # Increase event queue size
      CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE: "64"
      # Optimize for low latency
      CONFIG_FREERTOS_USE_TICKLESS_IDLE: "n"
      # Logging optimizations
      CONFIG_LOG_DEFAULT_LEVEL_INFO: "y"
      CONFIG_LOG_MAXIMUM_LEVEL_VERBOSE: "y"
      # Enable PSRAM (8MB on AtomS3)
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      # Increase lwIP sockets to prevent "Failed to create socket" errors
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_LWIP_MAX_ACTIVE_TCP: "16"
      CONFIG_LWIP_MAX_LISTENING_TCP: "16"

# Enable PSRAM
psram:
  mode: octal
  speed: 80MHz

# External components
external_components:
  - source: 
      type: local
      path: components
  - source:
      type: git
      url: https://github.com/ssieb/esphome
      ref: lp5562
    components: [ lp5562 ]
    refresh: 1min

# WiFi configuration
wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tigo-Server Fallback Hotspot"
    password: "12345678"

captive_portal:

# Enable logging
logger:
  level: INFO  # Change to DEBUG if you need detailed logs for troubleshooting
  baud_rate: 0  # Disable hardware logging since we use the UART for Tigo communication

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD"

# Safe mode for OTA recovery
safe_mode:
  num_attempts: 3
  reboot_timeout: 5min

# MQTT is handled natively by ESPHome through Home Assistant API
# No separate MQTT configuration needed

# Web Server (optional, basic ESPHome web interface)
# Comment out if using custom Tigo web server below
# web_server:
#   port: 80

# UART configuration for Tigo communication
uart:
  id: tigo_uart
  tx_pin: GPIO1   # TX pin (same as original - pin 1)
  rx_pin: GPIO3   # RX pin (same as original - pin 3) 
  baud_rate: 38400
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 8192  # Increased for 32MB PSRAM to reduce packet loss

# Tigo Monitor component - sensors will be created automatically!
tigo_monitor:
  id: tigo_hub
  uart_id: tigo_uart
  number_of_devices: 20
  update_interval: 30s

# Custom web server for comprehensive Tigo monitoring dashboard
tigo_server:
  id: tigo_web
  tigo_monitor_id: tigo_hub
  port: 80

# Configure your sensors below - add individual device sensors and/or the power sum sensor

# Tigo Monitor Control Buttons
button:
  - platform: tigo_monitor
    name: "Generate YAML Config"
    id: generate_yaml_button
    tigo_monitor_id: tigo_hub
    button_type: yaml_generator
  - platform: tigo_monitor
    name: "Print Device Mappings"
    id: device_mappings_button
    tigo_monitor_id: tigo_hub
    button_type: device_mappings
  - platform: tigo_monitor
    name: "Reset Node Table"
    id: reset_node_table_button
    tigo_monitor_id: tigo_hub
    button_type: reset_node_table

# COPY THE GENERATED SENSOR YAML FROM LOGS HERE:
sensor:
  # NEW: Power Sum Sensor - Automatically calculates total power from all Tigo devices
  - platform: tigo_monitor
    tigo_monitor_id: tigo_hub
    name: "Total System Power"
    id: total_system_power
    # Optional: Add filters for smoothing
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

  # NEW: Energy Sum Sensor - Automatically calculates total kWh produced by all Tigo devices
  - platform: tigo_monitor
    tigo_monitor_id: tigo_hub
    name: "Total System Energy"
    id: total_system_energy

  # NEW: Device Count Sensor - Shows the number of discovered Tigo devices
  - platform: tigo_monitor
    tigo_monitor_id: tigo_hub
    name: "Discovered Devices Count"
    id: discovered_devices_count

  # System monitoring sensors
  - platform: wifi_signal
    name: "Tigo Server WiFi Signal"
    id: wifi_rssi
    update_interval: 60s

  - platform: uptime
    name: "Tigo Server Uptime"
    id: uptime_sensor

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Tigo Server IP Address"
    ssid:
      name: "Tigo Server Connected SSID"
  
  - platform: version
    name: "Tigo Server ESPHome Version"

# Optional: Binary sensors
binary_sensor:
  - platform: status
    name: "Tigo Server Status"

# Optional: Switches for control
switch:
  - platform: restart
    name: "Tigo Server Restart"

# Time component (optional, for logging timestamps)
time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Berlin"  # Adjust for your timezone

