import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import tigo_monitor, light
from esphome.const import CONF_ID, CONF_PORT
from pathlib import Path

DEPENDENCIES = ['tigo_monitor']
CODEOWNERS = ['@yourusername']

tigo_server_ns = cg.esphome_ns.namespace('tigo_server')
TigoWebServer = tigo_server_ns.class_('TigoWebServer', cg.Component)

CONF_TIGO_MONITOR_ID = 'tigo_monitor_id'
CONF_API_TOKEN = 'api_token'
CONF_WEB_USERNAME = 'web_username'
CONF_WEB_PASSWORD = 'web_password'
CONF_BACKLIGHT = 'backlight'

CONFIG_SCHEMA = cv.Schema({
    cv.GenerateID(): cv.declare_id(TigoWebServer),
    cv.GenerateID(CONF_TIGO_MONITOR_ID): cv.use_id(tigo_monitor.TigoMonitorComponent),
    cv.Optional(CONF_PORT, default=80): cv.port,
    cv.Optional(CONF_API_TOKEN): cv.string,
    cv.Optional(CONF_WEB_USERNAME): cv.string,
    cv.Optional(CONF_WEB_PASSWORD): cv.string,
    cv.Optional(CONF_BACKLIGHT): cv.use_id(light.LightState),
}).extend(cv.COMPONENT_SCHEMA)


# ---------------------------------------------------------------------------
# HTML asset embedding
# ---------------------------------------------------------------------------
# Each web/<page>.html file becomes two C++ raw-string constants in the
# generated `web_assets.h`: <PAGE>_HTML_PRE and <PAGE>_HTML_POST, split at the
# `__TIGO_API_TOKEN__` placeholder. Handlers send PRE + api_token_ + POST so
# the runtime substitution stays exactly as it was before extraction.
#
# Pages without the placeholder get one constant: <PAGE>_HTML.
#
# The header is regenerated on every config — the .html files are the source
# of truth, and the generated header is a build artifact (gitignored).

WEB_PAGES = ['dashboard', 'nodes', 'status', 'yaml', 'cca', 'history']
TOKEN_PLACEHOLDER = '__TIGO_API_TOKEN__'


def _pick_raw_delim(content: str) -> str:
    """Find a raw-string delimiter that doesn't appear in `content`."""
    delim = 'TIGO'
    while f'){delim}"' in content:
        delim += 'X'
    return delim


def _generate_web_assets_header():
    """Write web_assets.h alongside tigo_web_server.cpp.

    Reads each web/<page>.html, splits at the API-token placeholder, and emits
    raw C++ string constants. Re-run on every codegen pass so the header
    tracks the .html source files.
    """
    component_dir = Path(__file__).parent
    web_dir = component_dir / 'web'
    out = component_dir / 'web_assets.h'

    lines = [
        '// Auto-generated by tigo_server/__init__.py — do not edit.',
        '// Source: components/tigo_server/web/*.html',
        '#pragma once',
        'namespace esphome {',
        'namespace tigo_server {',
        '',
    ]

    for page in WEB_PAGES:
        path = web_dir / f'{page}.html'
        if not path.exists():
            raise FileNotFoundError(f'expected web asset {path}')
        content = path.read_text()
        const_base = f'{page.upper()}_HTML'
        if TOKEN_PLACEHOLDER in content:
            pre, post = content.split(TOKEN_PLACEHOLDER, 1)
            d_pre = _pick_raw_delim(pre)
            d_post = _pick_raw_delim(post)
            lines.append(
                f'inline constexpr const char {const_base}_PRE[] = '
                f'R"{d_pre}({pre}){d_pre}";'
            )
            lines.append(
                f'inline constexpr const char {const_base}_POST[] = '
                f'R"{d_post}({post}){d_post}";'
            )
        else:
            d = _pick_raw_delim(content)
            lines.append(
                f'inline constexpr const char {const_base}[] = '
                f'R"{d}({content}){d}";'
            )
        lines.append('')

    lines += ['}  // namespace tigo_server', '}  // namespace esphome', '']
    out.write_text('\n'.join(lines))


_generate_web_assets_header()


async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)

    # Get the tigo_monitor component
    parent = await cg.get_variable(config[CONF_TIGO_MONITOR_ID])
    cg.add(var.set_tigo_monitor(parent))

    # Set the port
    cg.add(var.set_port(config[CONF_PORT]))

    # Set the API token if provided
    if CONF_API_TOKEN in config:
        cg.add(var.set_api_token(config[CONF_API_TOKEN]))

    # Set the web authentication if provided
    if CONF_WEB_USERNAME in config:
        cg.add(var.set_web_username(config[CONF_WEB_USERNAME]))
    if CONF_WEB_PASSWORD in config:
        cg.add(var.set_web_password(config[CONF_WEB_PASSWORD]))

    # Set the backlight if provided
    if CONF_BACKLIGHT in config:
        backlight = await cg.get_variable(config[CONF_BACKLIGHT])
        cg.add(var.set_backlight(backlight))
