# M5Stack AtomS3R Display Package
# 128x128 LCD screen showing Tigo Monitor status
# Include this package in your config to enable the display
#
# IMPORTANT: Display updates compete with UART processing. To minimize missed packets:
# 1. Increase UART RX buffer: CONFIG_UART_RX_BUFFER_SIZE: "8192" or higher
# 2. TX buffer can stay small (1024) since we only listen to the bus
# 3. Increase display update_interval to 5s or more (default below)
# 4. Consider disabling light effects during peak solar hours
# 5. The component automatically processes 4KB per loop to handle display overhead

# External component for LP5562 LED driver
external_components:
  - source:
      type: git
      url: https://github.com/RAR/esphome-lp5562
    components: [ lp5562 ]

# I2C bus for LP5562 (RGB LED + LCD Backlight control)
i2c:
  sda: GPIO38  # SYS_SDA
  scl: GPIO39  # SYS_SCL
  scan: true

# LP5562 LED driver (controls RGB indicator LED + LCD backlight)
lp5562:
  id: rgb_driver
  address: 0x30

# SPI bus for the LCD
spi:
  clk_pin: GPIO15
  mosi_pin: GPIO21

# Outputs for LP5562 channels
output:
  - platform: lp5562
    id: lp5562_red
    lp5562_id: rgb_driver
    channel: 0  # Red channel
  - platform: lp5562
    id: lp5562_green
    lp5562_id: rgb_driver
    channel: 1  # Green channel
  - platform: lp5562
    id: lp5562_blue
    lp5562_id: rgb_driver
    channel: 2  # Blue channel
  - platform: lp5562
    id: backlight_output
    lp5562_id: rgb_driver
    channel: 3  # White channel (LCD backlight)

# Light entities
light:
  # RGB indicator LED
  - platform: rgb
    name: "RGB LED"
    id: status_led
    red: lp5562_red
    green: lp5562_green
    blue: lp5562_blue
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1s
          update_interval: 1s
      - strobe:
          name: "Strobe"

  # LCD Backlight (LP5562 White Channel)
  - platform: monochromatic
    name: "LCD Backlight"
    id: lcd_backlight
    output: backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 0.5s

# Display configuration
display:
  - platform: st7789v
    id: atoms3r_lcd
    model: CUSTOM
    height: 128
    width: 128
    offset_height: 2
    offset_width: 1
    cs_pin: GPIO14
    dc_pin: GPIO42
    reset_pin: GPIO48
    rotation: 0
    eightbitcolor: true
    data_rate: 40MHz
    update_interval: 5s  # Increased from 2s to reduce CPU load and minimize missed UART packets
    setup_priority: -100  # Initialize display after everything else to avoid WDT timeout
    lambda: |-
      // Use cached values from tigo_monitor (updated during sensor publish)
      // This avoids iterating through 30+ devices on every display update
      int device_count = id(tigo_hub)->get_device_count();
      int online_count = id(tigo_hub)->get_online_device_count();
      float total_power = id(tigo_hub)->get_total_power();
      
      // Background
      it.fill(COLOR_BLACK);
      
      // Header - Title
      it.print(64, 5, id(font_title), COLOR_WHITE, TextAlign::TOP_CENTER, "TIGO");
      it.print(64, 20, id(font_small), Color(150, 150, 150), TextAlign::TOP_CENTER, "Solar Monitor");
      
      // Divider line
      it.line(10, 35, 118, 35, Color(100, 100, 100));
      
      // Main stats
      if (device_count > 0) {
        // Total Power - Large and prominent
        it.printf(64, 45, id(font_large), COLOR_ORANGE, TextAlign::TOP_CENTER, "%.0fW", total_power);
        
        // Device status
        it.printf(64, 75, id(font_medium), COLOR_WHITE, TextAlign::TOP_CENTER, "%d/%d", online_count, device_count);
        it.print(64, 92, id(font_tiny), Color(150, 150, 150), TextAlign::TOP_CENTER, "devices online");
        
        // Status indicator
        if (online_count == device_count) {
          it.filled_circle(10, 110, 4, COLOR_GREEN);
          it.print(20, 107, id(font_small), COLOR_GREEN, TextAlign::CENTER_LEFT, "All OK");
        } else if (online_count > 0) {
          it.filled_circle(10, 110, 4, COLOR_ORANGE);
          it.printf(20, 107, id(font_small), COLOR_ORANGE, TextAlign::CENTER_LEFT, "%d Offline", device_count - online_count);
        } else {
          it.filled_circle(10, 110, 4, COLOR_RED);
          it.print(20, 107, id(font_small), COLOR_RED, TextAlign::CENTER_LEFT, "No Data");
        }
      } else {
        // No devices discovered yet
        it.print(64, 55, id(font_medium), Color(200, 200, 0), TextAlign::TOP_CENTER, "WAITING");
        it.print(64, 80, id(font_small), Color(150, 150, 150), TextAlign::TOP_CENTER, "for devices...");
        it.filled_circle(10, 110, 4, Color(200, 200, 0));
        it.print(20, 107, id(font_small), Color(200, 200, 0), TextAlign::CENTER_LEFT, "Scanning");
      }
      
      // WiFi status indicator (top right)
      if (id(wifi_status).state) {
        it.filled_circle(118, 10, 3, COLOR_GREEN);
      } else {
        it.filled_circle(118, 10, 3, COLOR_RED);
      }

# Color definitions
color:
  - id: COLOR_BLACK
    red: 0%
    green: 0%
    blue: 0%
  - id: COLOR_WHITE
    red: 100%
    green: 100%
    blue: 100%
  - id: COLOR_GREEN
    red: 0%
    green: 100%
    blue: 0%
  - id: COLOR_RED
    red: 100%
    green: 0%
    blue: 0%
  - id: COLOR_ORANGE
    red: 100%
    green: 65%
    blue: 0%

# Fonts for the display
font:
  - file: "gfonts://Roboto@bold"
    id: font_title
    size: 14
  - file: "gfonts://Roboto@bold"
    id: font_large
    size: 28
  - file: "gfonts://Roboto"
    id: font_medium
    size: 18
  - file: "gfonts://Roboto"
    id: font_small
    size: 12
  - file: "gfonts://Roboto"
    id: font_tiny
    size: 9

# WiFi status sensor for display indicator
binary_sensor:
  - platform: status
    id: wifi_status
    internal: true

# Configure tigo_server to control the backlight from web UI
tigo_server:
  backlight: lcd_backlight
