# ESP32-P4 Evaluation Board Configuration
# 32MB PSRAM, 400MHz Dual-Core, Octal PSRAM
# Recommended for: Large installations (50+ devices)
# Optimized for maximum performance and minimal packet loss

esphome:
  name: tigo-server
  friendly_name: "Tigo Server P4"

esp32:
  board: esp32-p4-function-ev-board
  variant: esp32p4
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # CPU frequency (P4 runs at 400MHz)
      CONFIG_ESP32P4_DEFAULT_CPU_FREQ_400: "y"
      
      # UART optimizations - aggressive settings for 32MB PSRAM
      CONFIG_UART_ISR_IN_IRAM: "y"
      CONFIG_UART_RX_BUFFER_SIZE: "16384"  # 16KB RX buffer
      CONFIG_UART_TX_BUFFER_SIZE: "4096"   # 4KB TX buffer
      
      # High-frequency FreeRTOS tick for better interrupt responsiveness
      CONFIG_FREERTOS_HZ: "1000"  # 1ms tick instead of 10ms
      
      # Increase event queue size for high throughput
      CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE: "128"
      
      # Disable tickless idle to reduce interrupt latency
      CONFIG_FREERTOS_USE_TICKLESS_IDLE: "n"
      
      # Increase lwIP sockets for HTTP operations
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_LWIP_MAX_ACTIVE_TCP: "16"
      CONFIG_LWIP_MAX_LISTENING_TCP: "16"
      
# Enable PSRAM with maximum speed
psram:
  mode: hex
  speed: 200MHz  # P4 supports higher PSRAM speeds

# UART configuration for Tigo communication
uart:
  id: tigo_uart
  tx_pin: GPIO1   # Adjust based on your P4 board pinout
  rx_pin: GPIO3   # Adjust based on your P4 board pinout
  baud_rate: 38400
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 16384  # Match SDK buffer for consistency

# Tigo Monitor component - configured for large installations
tigo_monitor:
  id: tigo_hub
  uart_id: tigo_uart
  number_of_devices: 100  # P4 can handle much larger installations
  update_interval: 30s

# Custom web server
tigo_server:
  id: tigo_web
  tigo_monitor_id: tigo_hub
  port: 80
